### ISSUE TITLE
Compiled app panicking but when run `cargo run` works fine. 

### ISSUE THREAD

**Issue by andreacoi** [andreacoi/dotupdater#1]
thread 'main' panicked at src/main.rs:126:10:
Unable to read TOML file. Is the correct path, isn't it?: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by andreacoi** [comment]
full backtrace:

thread 'main' panicked at src/main.rs:126:10:
Unable to read TOML file. Is the correct path, isn't it?: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x55eda25ba1ea - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x55eda25dd4db - core::fmt::write::hf5713710ce10ff22
   2:     0x55eda25b78a3 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x55eda25bb392 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x55eda25baffe - std::panicking::default_hook::h81c8cd2e7c59ee33
   5:     0x55eda25bbc1f - std::panicking::rust_panic_with_hook::had2118629c312a4a
   6:     0x55eda25bb907 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   7:     0x55eda25ba6c9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   8:     0x55eda25bb594 - rust_begin_unwind
   9:     0x55eda24b8893 - core::panicking::panic_fmt::h3eea515d05f7a35e
  10:     0x55eda24b8d06 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
  11:     0x55eda24c6d8e - dotupdater::main::h78b737b199277c8a
  12:     0x55eda24cac53 - std::sys::backtrace::__rust_begin_short_backtrace::h26ff9615c3cbec56
  13:     0x55eda24ca909 - std::rt::lang_start::{{closure}}::h0f61ff1b18f2d3f7
  14:     0x55eda25b4510 - std::rt::lang_start_internal::h4d90db0530245041
  15:     0x55eda24c7275 - main
  16:     0x7f25ee44624a - <unknown>
  17:     0x7f25ee446305 - __libc_start_main
  18:     0x55eda24b9041 - _start
  19:                0x0 - <unknown>

**Comment by andreacoi** [comment]
Solved.
It was my fault. Made a typo to launch app. I launched it by typing "dotupdater" instead of "./dotupdater".
